### ISSUE TITLE
Please consider reducing the cask update to 1h instead of the 24h from master

### ISSUE THREAD

**Issue by lakdif** [PikachuEXE/homebrew-FreeTube#32]
Unless I'm missing something, the whole thing is just packaging upstream, because apparently they refuse to make
an arm64 build of the app. This is nonsence to me, since you can just right click on the untrusted app and choose "Open"
from the context menu to avoid doing the **xattr -cr /Applications/FreeTube.app** command.
This will prompt the "unsafe" screen from MacOS but will still allow you to open it.

So anyway an update can run almost seamlessly. And users who install FreeTube are power users, so a small readme
will be more than enough to show the proper instructions.

The cask produced here is just a yarn run build:arm64 so I really can't understand why it's not upstreamed.

**Comment by PikachuEXE** [comment]
You can build the app yourself or convince on upstream repo to setup an official tap
This is my personal tap and does not represent official FT team at all
Closing in 24h

**Comment by PikachuEXE** [comment]
Totally agree, I did not check the commit line by line:

https://github.com/PikachuEXE/homebrew-FreeTube/commit/1a7f9c14139f7d8b4065b55ab99789b44e246fd8

Updated in https://github.com/PikachuEXE/homebrew-FreeTube/commit/0cac9ef6ef0b55514958d39f956d423d3acb251f

**Comment by PikachuEXE** [comment]
Please ask FT team for making Homebrew Tap / arm64 build. I am just one dev (and I build my own build with custom additions)

https://github.com/FreeTubeApp/FreeTube/issues/2786
